In [8]:
import pandas as pd

dados1 = pd.read_csv("dados1.csv", sep=';')
dados2 = pd.read_csv('dados2.csv', sep=';')
print("Dados 1:")
print(dados1.head())

Dados 1:
       municipio  posicao              candidato partido  votos pct_validos
0  Abdon Batista        1       Flávio Bolsonaro      PL   1188       61,43
1  Abdon Batista        2                   Lula      PT    547       28,28
2  Abdon Batista        3           Renan Santos  MISSÃO     71        3,67
3  Abdon Batista        4  Escritor Augusto Cury  AVANTE     64        3,31
4  Abdon Batista        5         Ronaldo Caiado     PSD     42        2,17

In [7]:
print("Dados 2:")
print(dados2.head(10))

Dados 2:
          municipio  eleitorado  comparecimento  abstencao  votos_validos  \
0     Abdon Batista        2484            2014        470           1934
1      Abelardo Luz        9660            7934       1726           7594
2        Agrolândia        8289            6581       1708           6324
3        Agronômica        5556            4499       1057           4334
4         Água Doce        8337            6523       1814           6342
5  Águas de Chapecó       11614            9371       2243           8822
6       Águas Frias        6999            5507       1492           5296
7      Águas Mornas       21225           17895       3330          17036
8    Alfredo Wagner        7828            6157       1671           5946
9   Alto Bela Vista       14809           12174       2635          11500

   brancos  nulos       mais_votado
0       46     34  Flávio Bolsonaro
1       92    248  Flávio Bolsonaro
2      120    137  Flávio Bolsonaro
3       52    113  Flávio Bolsonaro
4       77    104  Flávio Bolsonaro
5      224    325  Flávio Bolsonaro
6       57    154  Flávio Bolsonaro
7      263    596  Flávio Bolsonaro
8      107    104  Flávio Bolsonaro
9      259    415  Flávio Bolsonaro

In [5]:
dados1

          municipio  posicao              candidato partido  votos pct_validos
0     Abdon Batista        1       Flávio Bolsonaro      PL   1188       61,43
1     Abdon Batista        2                   Lula      PT    547       28,28
2     Abdon Batista        3           Renan Santos  MISSÃO     71        3,67
3     Abdon Batista        4  Escritor Augusto Cury  AVANTE     64        3,31
4     Abdon Batista        5         Ronaldo Caiado     PSD     42        2,17
...             ...      ...                    ...     ...    ...         ...
2060         Zortéa        3           Renan Santos  MISSÃO    143        2,47
2061         Zortéa        4  Escritor Augusto Cury  AVANTE    127        2,19
2062         Zortéa        5         Ronaldo Caiado     PSD     95        1,64
2063         Zortéa        6                   Zema    NOVO     39        0,67
2064         Zortéa        7                 Samara      UP     21        0,36

[2065 rows x 6 columns]

In [6]:
dados2

,municipio,eleitorado,comparecimento,abstencao,votos_validos,brancos,nulos,mais_votado
0,Abdon Batista,2484,2014,470,1934,46,34,Flávio Bolsonaro
1,Abelardo Luz,9660,7934,1726,7594,92,248,Flávio Bolsonaro
2,Agrolândia,8289,6581,1708,6324,120,137,Flávio Bolsonaro
3,Agronômica,5556,4499,1057,4334,52,113,Flávio Bolsonaro
4,Água Doce,8337,6523,1814,6342,77,104,Flávio Bolsonaro
...,...,...,...,...,...,...,...,...
290,Witmarsum,3016,2467,549,2356,38,73,Flávio Bolsonaro
291,Xanxerê,3112,2395,717,2330,28,37,Flávio Bolsonaro
292,Xavantina,2271,1771,500,1695,39,37,Flávio Bolsonaro
293,Xaxim,7504,6442,1062,6202,107,133,Flávio Bolsonaro
294,Zortéa,7385,5974,1411,5787,80,107,Flávio Bolsonaro